### PR TITLE
Add riscv (esp32 chips) dependencies

### PR DESCRIPTION
**Pull request by potsrevennil**
This PR only setup environment for riscv (esp32 series)

There is #50 adding support for esp32c3 depends on this PR.

I'm not particularly sure about what'd be better for the folder structure of the static libraries provided by esp-idf.

Currently in `$ESP_IDF_DIR` or `$IDF_PATH` (they are alias set by the nix derivation), all the esp components source code reside in the `components` directory, headers should be included from here.

And there is `$ESP_IDF_LIB`, which had all the static linked libraries compiled from `esp-idf`, in the following folder structure, which mimics the esp-idf build system artifacts folder structure.
```
esp32c3
  |--- bootloader
  |        |--- esp-idf
  |                |--- components ...
  |                |--- ...
  |--- esp-idf
          |--- componens ...
          |--- ...
```
(There are some overlapped components in `esp-idf` and `bootloader`, the ones provided by `bootloader` are mostly smaller.)

[//]: # (SPDX-License-Identifier: CC-BY-4.0)
[//]: # (TODO Customize PR template)

[//]: # (See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository )

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)

### CODE REVIEW

**Comment by mkannwischer** [comment]
I tested that `nix develop` installs the required dependencies.
Afterwards, I do have `riscv32-esp-elf-gcc` in my PATH. 
I also checked that the arm (mps2-an386, stm32f4discovery) are still working fine. 

What's the reason for doing this in a separate PR to #50? This PR does not seem to be useful by itself, is it?

**Comment by potsrevennil** [comment]
Yeah, it's not useful by itself indeed, I just thought that to it'd be cleaner in the first place, since I also did some slight refactor on the nix files by the way.

**Comment by mkannwischer** [comment]
Okay, let's get #50 into shape first and then we can decide if we merge it together or separately. 
If you want it cleaner, then the refactoring of the existing nix files should be done first separately - but I don't think that's needed.

**Comment by potsrevennil** [comment]
I'd agree with you, probably we could just merge them together instead

**Comment by mkannwischer** [comment]
Closing this as it's included in #50

**Pull request closed without merging**
